spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # autoReconnect=true自动重连(mysql5以上无效)，allowMultiQueries=true支持批量更新
    url: jdbc:mysql://localhost:3306/view?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: lihy#520
  cloud:
    config:
      profile: dev
# mybatis mapper xml 配置
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml