spring:
  application:
    name: view-photo-service
  http:
    multipart:
      #Max file size，默认1M
      max-file-size: 2000Mb
      #Max request size，默认10M
      max-request-size: 2500Mb
management:
  security:
    enabled: false
