spring:
  application:
    name: view-photo-service
  http:
    multipart:
      #Max file size，默认1M
      max-file-size: 2000Mb
      #Max request size，默认10M
      max-request-size: 2500Mb
#在1.5.x版本中通过management.security.enabled=false来暴露所有端点
#management:
  #security:
    #enabled: false
